### PR TITLE
Gui fixes

### PR DESCRIPTION
**Pull request by hasso**
Two tiny fixes and one pretty major one. I'm not 100% right whether it's right, but that fixes the issue for me. Without it freshly started EdWare raises and exception about missing attribute while loading a program from file and leaves programming and variable areas blank until I force them to refresh somehow.

### CODE REVIEW

**Comment by Bdanilko** [comment]
Thanks Hasso -- hadn't seen the issue with the attribute, but makes sense. Also the colours have always worked for me, but your method is closer to the way it should be done according to the documentation. Changed lightgray to "light grey" to match your style.
Thanks!

**Comment by hasso** [comment]
About "lightblue" there was a message in the console.

About issue about missing attribute ... there is probably a more general fix for this. I just discovered another similar one. The problem seems to be that if you program normally, these issues will not appear because problematic attributes are initialised in <bric>_details() methods which are called as soon as you drag a bric into programming area. The point is that these methods are not called if you load program from file.

Load a program with read light bric and press a "Program Edison" button:

`Traceback (most recent call last):
  File "./edware.py", line 560, in on_program_button
    dialog = gui.downloader.audio_downloader("", "Download over audio")
  File "/Volumes/BigDisk/hasso/Code/GitHub/Edware/EdWare_src/gui/downloader.py", line 368, in __init__
    self.download_bytes, self.dtype, self.version = get_bytes(file_name)
  File "/Volumes/BigDisk/hasso/Code/GitHub/Edware/EdWare_src/gui/downloader.py", line 220, in get_bytes
    compile_file = write_code(file_name)
  File "/Volumes/BigDisk/hasso/Code/GitHub/Edware/EdWare_src/gui/downloader.py", line 163, in write_code
    win_data.get_all_code(file_handle)
  File "/Volumes/BigDisk/hasso/Code/GitHub/Edware/EdWare_src/gui/win_data.py", line 1204, in get_all_code
    get_code_stream(pdata.program.get_stream_id(stream), -1, in_event, code_lines)
  File "/Volumes/BigDisk/hasso/Code/GitHub/Edware/EdWare_src/gui/win_data.py", line 1110, in get_code_stream
    code_lines.extend(tdata.windows['detail'].generate_code(bric_id, in_event))
  File "/Volumes/BigDisk/hasso/Code/GitHub/Edware/EdWare_src/gui/detail_win.py", line 484, in generate_code
    converted = self.convert_dict[name](data, 'from_ids', name, bric_id)
  File "/Volumes/BigDisk/hasso/Code/GitHub/Edware/EdWare_src/gui/detail_win.py", line 1471, in readlight_convert
    output[0] = self.module_apply_alias(output[0], self.module_aliases)
AttributeError: 'Detail_win' object has no attribute 'module_aliases'`

**Comment by Bdanilko** [comment]
Hi Hasso,

Thanks for this detail, it should make it easier to find the issue. Which
OS are you using?

I find the colours a bit strange (and always have). The api says to use a
colour, but it kind of works with a colour name instead. Could be a python
addition.

Thanks again,
Brian

**Comment by hasso** [comment]
I'm using MacOSX Mavericks (10.9) mostly. Python (2.7.9) and wx-python (3.0.2) from MacPorts.

**Comment by Bdanilko** [comment]
Hi Hasso,

Yes, well caught! As you said, if the detail window wasn't displayed then
the module_aliases weren't set. That bug has been in since the new names to
be displayed for the events was introduced -- thanks for catching it.

I've pushed the fix to the repo, but won't do a new release until the
weekend (that point was more for Brenton)

Cheers,
Brian

**Comment by hasso** [comment]
What I meant that shouldn't be the problem with missing bad_events attribute of event icons fixed in better way as well? (The one I fixed in a hack way in the chunk 2 of this pull request).

**Pull request merged**
